package RocketControl
  import Modelica.Math.Vectors.norm;
  import Modelica.Units.SI;
  import Modelica.Units.NonSI;
  import Modelica.Mechanics.MultiBody;
  import Modelica.Units.Conversions.from_deg;
  import Modelica.Units.Conversions.to_deg;
  import Modelica.Constants.pi;
end RocketControl;
